extend coremap with function get_page_index(vaddr); alloc_kpages and free_kpages implemented, but need to be tested; have compiling errors...  undefined reference to vm_fault, so don't merge if you can not fix it